[package]
name = "bsptab-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x11rb = "0.11"
clap = { version = "4.1", features = ["derive"] }
clap-num = "*"
nonempty = "0.8"
